<?php
    date_default_timezone_set("Asia/Bangkok");
    include('../backend/database.php');
    include('../backend/function.php');
    session_start();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teac</title>
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
<nav>

        <div class="nav-left">
            <div class="header">Social media</div> 
            <ul>
                <a href="Home.php"><li><img src="../image/outline_home_white_24dp.png"> Home</li></a>
                <li><img src="../image/outline_groups_white_24dp.png"> Grouphs</li>
                <li><img src="../image/outline_drive_file_rename_outline_white_24dp.png"> Create</li>
                <li><img src="../image/outline_local_offer_white_24dp.png"> Tag</li>
            </ul>
        </div>
        <div class="nav-right">
            <div class="search-box">
                <img src="../image/outline_search_white_24dp.png">
                <input type="text" placeholder="Search">
            </div>
            <div class="nav-user-icon online">
                <img src="../image/outline_account_circle_white_24dp.png">
                <img src="../image/outline_logout_white_24dp.png">

            </div>
        </div>
    </nav>

    <section class="home" id="home">

    </section>

    <section section class="ex">
        <h1 class="heading"> <span>Announce</span></h1>
        <div class="box-container">
            <div class="box">
                <div class="head">Apple vs. Epic ruling reveals 70% of App Store
                    revenue comes from a small fraction of customers
                    playing games
                </div> <br>
                <div class="body">
                    Apple’s App Store revenue is made up almost entirely of users playing games, according to a court ruling
                    released Friday that concluded Epic Games failed to prove Apple is a monopolist.
                    According to the ruling, gaming apps account for approximately 70% of all App Store revenue. That 70%
                    is generated by less than 10% of all App Store users, the court said. By contrast, more than 80% of all
                    accounts generate virtually no revenue, as 80% of all apps on the App Store are free, according to the
                    document.
                    As of January, there were 1 billion active iPhones and 1.65 billion Apple devices in use around the globe.
                    Apple has for years taken a 30% cut of revenue from purchases in apps distributed through the App
                    Store. Developers have alleged that Apple’s App Store platform is unfair to smaller companies, and last
                    year Apple lowered the commission to 15% for apps with less than $1 million in annual net sales on its
                    platform.
                    On Friday, federal Judge Yvonne Gonzalez Rogers handed down the decision in the trial between Epic
                    and Apple, and ultimately issued an injunction that said Apple can’t prohibit developers from providing
                    links or other communication directing users away from Apple in-app purchasing.
                    The injunction goes into effect in December.
                    Apple doesn’t disclose how much revenue its App Store makes per year. Rather, the company releases
                    data points that include the total amount Apple has paid to developers since the App Store launched in
                    2008. According to a CNBC analysis, Apple’s App Store had gross sales of around $64 billion last year.
                    The company said earlier this year it has paid developers $200 billion since 2008, up $45 billion from
                    January 2020.
                </div>
            </div>
        </div>
        <br>
       
        <br>
        <div class="comments">
                    <?php
                        echo "
                            <form method='POST' action='".setComments($conn)."'>
                            <input type='hidden' name='uid' value='CM'>
                            <input type='hidden' name='date' value='".date('Y-m-d H:i:s')."'>
                            <textarea name='messages' class='Com'></textarea> <br>
                            <button type='submit' name='commentSubmit'>Comments</button>
                            </form>";
                    ?>
        </div>
        
    </section>

   <section class="footer">
        <div class="share">
                <a href="https://www.facebook.com/" target="_blank" class="fab fa-facebook-f"></a>
                <a href="https://twitter.com/" target="_blank" class="fab fa-twitter"></a>
                <a href="https://www.instagram.com/" target="_blank" class="fab fa-instagram"></a>
                <a href="https://www.google.com/" target="_blank" class="fab fa-google"></a>
        </div>

        <div class="credit">Created by <span>ISNE students</span> We all rights reserved</div>
   </section>
</body>
</html>